language: ruby
script: "bundle exec rake test"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
env:
  - PUPPET_GEM_VERSION=2.7.1
  - PUPPET_GEM_VERSION=3.7.2
  - PUPPET_GEM_VERSION=4.3.2
matrix:
  fast_finish: true
notifications:
  email: false
matrix:
  exclude:
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION=4.3.2
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION=2.7.1
    - rvm: 2.1
      env: PUPPET_GEM_VERSION=2.7.1
