language: ruby
script: "bundle exec rake test"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.4
env:
  - PUPPET_GEM_VERSION=2.7.14 RSPEC_PUPPET_VERSION=2.5.0
  - PUPPET_GEM_VERSION=3.8.5 RSPEC_PUPPET_VERSION=2.5.0
  - PUPPET_GEM_VERSION=4.10.9
  - PUPPET_GEM_VERSION=5.3.3
matrix:
  fast_finish: true
notifications:
  email: false
matrix:
  exclude:
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION=4.10.9
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION=5.3.3
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION=4.10.9
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION=5.3.3
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION=2.7.14 RSPEC_PUPPET_VERSION=2.5.0
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION=5.3.3
    - rvm: 2.1
      env: PUPPET_GEM_VERSION=2.7.14 RSPEC_PUPPET_VERSION=2.5.0
    - rvm: 2.1
      env: PUPPET_GEM_VERSION=5.3.3
    - rvm: 2.4
      env: PUPPET_GEM_VERSION=2.7.14 RSPEC_PUPPET_VERSION=2.5.0
    - rvm: 2.4
      env: PUPPET_GEM_VERSION=3.10.9 RSPEC_PUPPET_VERSION=2.5.0
